version: '2'
services:
  app:
    container_name: my-app
    build: .
    command: go run main.go
    volumes:
      - .:/app
    working_dir: /app
    ports:
      - "60:3001"
    environment:
      GO111MODULE: "on"
      PORT: 3001